### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by supmaxi** [eracknaphobia/plugin.video.crackle#1]
hi this addon has just stopped working

12:15:25 T:28872   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.crackle/?id=%2fmovies&mode=101
12:15:25 T:28872   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.crackle/?id=%2fmovies&mode=101) failed

website changes?

**Comment by eracknaphobia** [comment]
Sure sounds like it. Thanks for the heads up, I'll look into this.

**Comment by eracknaphobia** [comment]
FYI, The latest commit should have most everything back to working. Only catch is it's only 480p until I get the DRM figured out, which hopefully won't take too long.

**Comment by drcurry2010** [comment]
I'm having the same issue... Doesn't seem to matter if it's Kodi 17 or 18. Problem is pervasive across multiple Kodi versions and operating systems. Looking forward to a fix... Thanks for the hard work!

**Comment by supmaxi** [comment]
Excellent, its working!
They are playing in 540P which is not too bad

For the DRM, please dont force MPEG-Dash, because many people (myself included) are using Kodi 16 forks (with upgraded python / SSL) that work much better than Kodi 17 on Android (such as FTMC, SPMC , etc). If DRM can be implemented without it, that would be amazing - otherwise, maybe an option that needs to be enabled in the settings for those who want to use it.

Also, i have modified your latest commit, to include A-Z Movies, and A-Z TV Series options.
I also noticed that AU region API has a different selection of movies / shows (some that are not available in the US region). I also implemented those categories - however, i greyed them out because for some reason, the movies which are extra in the AU region, dont seem to play (getting error message).
So ill leave that to you to see if you want to figure it out (not a big deal) :)
Note: its not a geo-issue, because im located in AU.
However, an interesting thing is that if i try to play those movies in my internet browser (with tracking blocked by my AV - they also dont play) - but once i remove the tracking block - they work. (maybe need to add a line to the end of the URL to confirm region etc, as its not IP based.)

Here is the link to the zip file if you want to check it out: http://s000.tinyupload.com/index.php?file_id=29198287842035941931
