### ISSUE TITLE
sorting of items now by name, not date

### ISSUE THREAD

**Issue by jjplano** [eracknaphobia/plugin.video.crackle#10]
hi! love your addon, since the last update is working great!

but now items are sorted by name inside of tv shows, not by date. this is a huge inconvenience, as you want to watch them on a chronological order, not by their title. and there's no option to change this inside the addon

please change it back!!

thanks!

**Comment by eracknaphobia** [comment]
That's no good. I will look into a fix.

**Comment by eracknaphobia** [comment]
Fix should has been submitted to the official kodi repo. Keep an eye out for version 2020.10.7 for the fix.

**Comment by jjplano** [comment]
that's great! thank you so much

keep up the good work
