### ISSUE TITLE
Please add support for Kodi IPTV Merge /Manager addons !

### ISSUE THREAD

**Issue by siliconhippy** [eracknaphobia/plugin.video.crackle#16]
Hi !

Great job, nice streams. Mostly work in Nexus, but issues with TV especially.

Kindly check:
https://github.com/matthuisman/slyguy.addons/issues/382

**Comment by eracknaphobia** [comment]
Crackle doesn't have live tv or epg info? It's all VOD sorted by category. I don't see how this would work with IPTV?
