### ISSUE TITLE
Please check Crackle

### ISSUE THREAD

**Issue by JayDee696969** [eracknaphobia/plugin.video.crackle#21]
Unfortunately, it is no longer working.

**Comment by eracknaphobia** [comment]
Thanks for reporting. Looks like the endpoints I was using have changed, I'm working on a fix...

**Comment by eracknaphobia** [comment]
This addon should work now. However, playback is only possible on android devices due to widevine vmp.

**Comment by BugfinderPro135** [comment]
Still not working for me on Android TV, Kodi version 21.2. It generates an error when a category is clicked on - ie. TV Shows - Classics...... No programs are fetched..... Try for yourself....
