### ISSUE TITLE
Can't see newer version 2020.2.13 for installation on Kodi 18.7

### ISSUE THREAD

**Issue by ssreekanth** [eracknaphobia/plugin.video.crackle#8]
I noticed plugin is updated for python 3 in [this commit](https://github.com/eracknaphobia/plugin.video.crackle/commit/a05491270d732cfa10aa8629ccf278a716f4748b).
Does that mean it is not supported on Kodi 18.x or lower anymore?

**Comment by eracknaphobia** [comment]
No, it'll work in both. That commit only added code for the upcoming Kodi 19 and is still a work in progress.

**Comment by ssreekanth** [comment]
I'm on 18.7, but can't see 2020.2.13 update on it.

**Comment by eracknaphobia** [comment]
That's because the code has not been pushed to my personal (eracknaphobia's repo) or kodi's repo. I am working on releasing an updated version soon, for now this code is only in this repo.

**Comment by ssreekanth** [comment]
Closing this issue then.
